# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yahoo-local}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Johnny Khai Nguyen"]
  s.date = %q{2010-05-25}
  s.description = %q{Ruby wrapper for the Yahoo! Local Search API}
  s.email = %q{johnnyn@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/yahoo_local.rb",
     "lib/yahoo_local/client.rb",
     "pkg/yahoo-local-0.1.0.gem",
     "pkg/yahoo-local-0.1.1.gem",
     "pkg/yahoo-local-0.1.2.gem",
     "tasks/yahoo_local_tasks.rake",
     "test/test_helper.rb",
     "test/yahoo_local_test.rb",
     "uninstall.rb",
     "yahoo-local.gemspec"
  ]
  s.homepage = %q{http://github.com/phuphighter/yahoo_local}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for the Yahoo! Local Search API}
  s.test_files = [
    "test/test_helper.rb",
     "test/yahoo_local_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.0"])
  end
end

